---

name: MSRN_x3
gops: 122.539
scale:
  3
shapes:
  - [1, 3, 100, 100]
cali_dataset:
  /workspace/model-zoo/dataset/DIV2K/DIV2K_test_LR_bicubic/X$(scale)
test_input:
  $(cali_dataset)/0987x$(scale).png

precision: true

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/MSRN_x$(scale).onnx
    --input_shapes [$(shape_param)]
    --keep_aspect_ratio
    --pixel_format rgb
    --test_input $(test_input)
    --test_result $(name)_outputs.npz
    --mlir $(workdir)/$(name).mlir

# mlir_calibration:
#   run_calibration.py $(workdir)/$(name).mlir
#     --dataset $(cali_dataset)
#     --input_num 100
#     -o $(home)/$(name)_cali_table

BM1684X:
  deploy:
    - model_deploy.py
        --mlir $(workdir)/$(name).mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_outputs.npz
        --tolerance 0.85,0.45
        --model $(workdir)/$(name)_1684x_f32.bmodel
    - model_deploy.py
        --mlir $(workdir)/$(name).mlir
        --quantize F16
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_outputs.npz
        --tolerance 0.85,0.45
        --model $(workdir)/$(name)_1684x_f16.bmodel
    - model_deploy.py
        --mlir $(workdir)/$(name).mlir
        --quantize INT8
        --calibration_table $(home)/$(name)_cali_table
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_outputs.npz
        --tolerance 0.85,0.45
        --model $(workdir)/$(name)_1684x_int8_sym.bmodel

  dataset:
    lr_dir: ./dataset/Set14/LR_bicubic/X$(scale)
    hr_dir: ./dataset/Set14/HR
    mean: [0, 0, 0]
    scale: [1, 1, 1]
    bgr2rgb: true
    self_ensemble: false
    criterion: ['psnr', 'ssim', 'lpips']

  harness:
    type: sr
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_1684x_f32.bmodel
        overlap: [6, 6]
        blend: false
        output_dir: $(workdir)/output_images_f32/
        threads: 2
      - name: FP16
        bmodel: $(workdir)/$(name)_1684x_f16.bmodel
        overlap: [6, 6]
        blend: false
        output_dir: $(workdir)/output_images_f16/
        threads: 2
      - name: INT8
        bmodel: $(workdir)/$(name)_1684x_int8_sym.bmodel
        overlap: [6, 6]
        blend: false
        output_dir: $(workdir)/output_images_int8/
        threads: 2
